USE [GDELT]
GO

/****** Object:  Table [COMMON].[DimFlag]    Script Date: 2015-03-15 11:41:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [COMMON].[DimFlag](
	[FlagKey] [tinyint] NOT NULL,
	[FlagDesc] [varchar](255) NOT NULL,
 CONSTRAINT [PK_DimFlag] PRIMARY KEY CLUSTERED 
(
	[FlagKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

