USE [GDELT]
GO

/****** Object:  Table [dbo].[DimActor]    Script Date: 13/01/2015 6:51:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DimActor](
	[ActorKey] [int] NOT NULL,
	[ActorName] [varchar](255) NOT NULL,
 CONSTRAINT [PK_DimActor] PRIMARY KEY CLUSTERED 
(
	[ActorKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC_ActorName] UNIQUE NONCLUSTERED 
(
	[ActorName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DimActor] ADD  CONSTRAINT [DFT_ActorKey]  DEFAULT (NEXT VALUE FOR [dbo].[SeqActorKey]) FOR [ActorKey]
GO

