USE [GDELT]
GO

/****** Object:  Table [dbo].[DimActorType]    Script Date: 13/01/2015 6:52:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DimActorType](
	[ActorTypeKey] [varchar](50) NOT NULL,
	[ActorTypeDescription] [varchar](255) NOT NULL,
 CONSTRAINT [PK_DimActorType] PRIMARY KEY CLUSTERED 
(
	[ActorTypeKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

