USE [GDELT]
GO

/****** Object:  Table [dbo].[DimGeoType]    Script Date: 13/01/2015 6:54:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DimGeoType](
	[GeoTypeKey] [int] NOT NULL,
	[GeoTypeCode] [char](1) NOT NULL,
	[GeoTypeDescription] [varchar](255) NOT NULL,
 CONSTRAINT [PK_DimGeoType] PRIMARY KEY CLUSTERED 
(
	[GeoTypeKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

