USE [GDELT]
GO

/****** Object:  Table [dbo].[DimDate]    Script Date: 2015-02-14 07:13:33 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DimDate](
	[DATE_KEY] [int] NOT NULL,
	[FULL_DATE] [datetime2](0) NOT NULL,
	[DATE_YYYYMMDD] [varchar](10) NULL,
	[DATE_MMDDYYYY] [varchar](10) NULL,
	[DATE_DDMMYYYY] [varchar](10) NULL,
	[DAY_OF_WEEK] [smallint] NULL,
	[DAY_OF_WEEK_NAME] [varchar](10) NULL,
	[DAY_OF_WEEK_ABBREVIATION] [varchar](3) NULL,
	[DAY_OF_MONTH] [smallint] NULL,
	[DAY_OF_YEAR] [smallint] NULL,
	[WEEKDAY_WEEKEND] [varchar](7) NULL,
	[IS_WEEKDAY] [tinyint] NULL,
	[WEEK_OF_YEAR] [tinyint] NULL,
	[MONTH_NAME] [varchar](10) NULL,
	[MONTH_ABBREVIATION] [varchar](3) NULL,
	[MONTH_OF_YEAR] [smallint] NULL,
	[IS_LAST_DAY_OF_MONTH] [tinyint] NULL,
	[CALENDAR_QUARTER] [smallint] NULL,
	[CALENDAR_QUARTER_NAME] [varchar](3) NULL,
	[CALENDAR_YEAR] [smallint] NULL,
	[CALENDAR_YEAR_NAME] [varchar](7) NULL,
	[CALENDAR_YEAR_MONTH] [varchar](16) NULL,
	[CALENDAR_YEAR_QUARTER] [varchar](12) NULL,
	[FISCAL_MONTH_OF_YEAR] [smallint] NULL,
	[FISCAL_QUARTER] [smallint] NULL,
	[FISCAL_QUARTER_NAME] [varchar](3) NULL,
	[FISCAL_YEAR] [smallint] NULL,
	[FISCAL_YEAR_NAME] [varchar](10) NULL,
	[FISCAL_YEAR_MONTH] [varchar](19) NULL,
	[FISCAL_YEAR_QUARTER] [varchar](15) NULL,
	[LAST_DAY_OF_WEEK] [datetime2](0) NOT NULL,
	[LAST_DAY_OF_MONTH] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_DATE_DIMENSION] PRIMARY KEY CLUSTERED 
(
	[DATE_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

