USE [GDELT]
GO

/****** Object:  Table [dbo].[DimGeoName]    Script Date: 13/01/2015 6:54:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DimGeoName](
	[GeoNameKey] [int] NOT NULL,
	[GeoName] [varchar](255) NOT NULL,
 CONSTRAINT [PK_DimGeoName] PRIMARY KEY CLUSTERED 
(
	[GeoNameKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC_DimGeoName_GeoName] UNIQUE NONCLUSTERED 
(
	[GeoName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DimGeoName] ADD  CONSTRAINT [DFT_GeoNameKey]  DEFAULT (NEXT VALUE FOR [dbo].[SeqGeoNameKey]) FOR [GeoNameKey]
GO

