USE [GDELT]
GO

/****** Object:  Table [GDELT20].[DimQuadClass]    Script Date: 2015-03-15 11:42:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [GDELT20].[DimQuadClass](
	[QuadClassKey] [int] NOT NULL,
	[QuadClassCode] [char](1) NOT NULL,
	[QuadClassDescription] [varchar](255) NOT NULL,
 CONSTRAINT [PK_DimQuadClass] PRIMARY KEY CLUSTERED 
(
	[QuadClassKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

